<div style= "text-align:center">
    <span style = "font-size:26px;border-bottom:2px solid teal">Olist E-commerce Data Analytics Project</span>
</div>

#### Notebook 01: Exploratory Data Analysis

In [2]:
import pandas as pd
import os 

# Defining Data Path using OS module for portability
DATA_PATH = os.path.join("..","Data","raw")

# Load Datasets
customers = pd.read_csv(os.path.join(DATA_PATH, "olist_customers_dataset.csv"))
geolocation = pd.read_csv(os.path.join(DATA_PATH, "olist_geolocation_dataset.csv"))
order_items = pd.read_csv(os.path.join(DATA_PATH, "olist_order_items_dataset.csv"))
payments = pd.read_csv(os.path.join(DATA_PATH, "olist_order_payments_dataset.csv"))
reviews = pd.read_csv(os.path.join(DATA_PATH, "olist_order_reviews_dataset.csv"))
orders = pd.read_csv(os.path.join(DATA_PATH, "olist_orders_dataset.csv"))
products = pd.read_csv(os.path.join(DATA_PATH, "olist_products_dataset.csv"))
sellers = pd.read_csv(os.path.join(DATA_PATH, "olist_sellers_dataset.csv"))
category_name_translation = pd.read_csv(os.path.join(DATA_PATH, "product_category_name_translation.csv"))

In [3]:
# Quick overview
datasets = {
    "customers":customers,
    "geolocation":geolocation,
    "order_items":order_items,
    "payments":payments,
    "reviews":reviews,
    "orders":orders,
    "products":products,
    "sellers":sellers,
    "category_name_translation":category_name_translation
}

for name, df in datasets.items():
    print(f"{name:25} : {df.shape[0]:,} rows x {df.shape[1]} columns")

customers                 : 99,441 rows x 5 columns
geolocation               : 1,000,163 rows x 5 columns
order_items               : 112,650 rows x 7 columns
payments                  : 103,886 rows x 5 columns
reviews                   : 99,224 rows x 7 columns
orders                    : 99,441 rows x 8 columns
products                  : 32,951 rows x 9 columns
sellers                   : 3,095 rows x 4 columns
category_name_translation : 71 rows x 2 columns

In [4]:
# Detailed overview 
for name, df in datasets.items():
    print(f"{name.upper()} DATASET")
    print("\nData types and Info")
    print("-" * 20)
    df.info()
    display(df.head(3))
    print(f"Total_missing_value_count : {df.isnull().sum().sum()}")
    print(f"Total_duplicate_rows : {df.duplicated().sum():,}")
    print("-" * 145,"\n")

CUSTOMERS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

Total_missing_value_count : 0
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

GEOLOCATION DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

Total_missing_value_count : 0
Total_duplicate_rows : 261,831
-------------------------------------------------------------------------------------------------------------------------------------------------

ORDER_ITEMS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

Total_missing_value_count : 0
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

PAYMENTS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

Total_missing_value_count : 0
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

REVIEWS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

Total_missing_value_count : 145903
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

ORDERS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

Total_missing_value_count : 4908
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

PRODUCTS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

Total_missing_value_count : 2448
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

SELLERS DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

Total_missing_value_count : 0
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

CATEGORY_NAME_TRANSLATION DATASET

Data types and Info
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

Total_missing_value_count : 0
Total_duplicate_rows : 0
-------------------------------------------------------------------------------------------------------------------------------------------------

In [5]:
# statistical analysis 
for name, df in datasets.items():
    print(f"{name.upper()} DATASET")
    display(df.describe())
    print("-" * 145,"\n")

CUSTOMERS DATASET

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

-------------------------------------------------------------------------------------------------------------------------------------------------

GEOLOCATION DATASET

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

-------------------------------------------------------------------------------------------------------------------------------------------------

ORDER_ITEMS DATASET

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

-------------------------------------------------------------------------------------------------------------------------------------------------

PAYMENTS DATASET

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

-------------------------------------------------------------------------------------------------------------------------------------------------

REVIEWS DATASET

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

-------------------------------------------------------------------------------------------------------------------------------------------------

ORDERS DATASET

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

-------------------------------------------------------------------------------------------------------------------------------------------------

PRODUCTS DATASET

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

-------------------------------------------------------------------------------------------------------------------------------------------------

SELLERS DATASET

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

-------------------------------------------------------------------------------------------------------------------------------------------------

CATEGORY_NAME_TRANSLATION DATASET

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

-------------------------------------------------------------------------------------------------------------------------------------------------

In [31]:
# Save summery report 
summery = {
    "Dataset":[],
    "Rows":[],
    "Columns":[],
    "Total_Missing_values":[],
    "Total_duplicate_rows":[]
}
for name,df in datasets.items():
    summery["Dataset"].append(name)
    summery["Rows"].append(f"{df.shape[0]:,}")
    summery["Columns"].append(df.shape[1])
    summery["Total_Missing_values"].append(f"{df.isnull().sum().sum():,}")
    summery["Total_duplicate_rows"].append(f"{df.duplicated().sum():,}")

summery_df = pd.DataFrame(summery)
summery_df.to_csv(os.path.join("..","Reports","Summery_report.csv"),index = False)
summery_df

,Dataset,Rows,Columns,Total_Missing_values,Total_duplicate_rows
0,customers,"99,441",5,0,0
1,geolocation,"1,000,163",5,0,"261,831"
2,order_items,"112,650",7,0,0
3,payments,"103,886",5,0,0
4,reviews,"99,224",7,"145,903",0
5,orders,"99,441",8,"4,908",0
6,products,"32,951",9,"2,448",0
7,sellers,"3,095",4,0,0
8,category_name_translation,71,2,0,0

In [30]:
# Save Missing value count per dataset 
all_missing = {
    "Dataset":[],
    "Column_names":[],
    "Missing_value_count":[],
    "Missing_count_percentage (%)":[]
}

for name,df in datasets.items():
    missing = df.isnull().sum()
    percent = (missing / len(df)) * 100

    for col in df.columns:
       if missing[col] > 0:
           all_missing["Dataset"].append(name)
           all_missing["Column_names"].append(col)
           all_missing["Missing_value_count"].append(missing[col])
           all_missing["Missing_count_percentage (%)"].append(percent[col])
        

missing_df = pd.DataFrame(all_missing)
missing_df.to_csv(os.path.join("..","Reports","Missing_value_count_report.csv"),index = False)
missing_df

,Dataset,Column_names,Missing_value_count,Missing_count_percentage (%)
0,reviews,review_comment_title,87656,88.341530
1,reviews,review_comment_message,58247,58.702532
2,orders,order_approved_at,160,0.160899
3,orders,order_delivered_carrier_date,1783,1.793023
4,orders,order_delivered_customer_date,2965,2.981668
5,products,product_category_name,610,1.851234
6,products,product_name_lenght,610,1.851234
7,products,product_description_lenght,610,1.851234
8,products,product_photos_qty,610,1.851234
9,products,product_weight_g,2,0.006070
10,products,product_length_cm,2,0.006070
11,products,product_height_cm,2,0.006070
12,products,product_width_cm,2,0.006070