<div style= "text-align:center">
    <span style = "font-size:26px;border-bottom:2px solid teal">Olist E-commerce Data Analytics Project</span>
</div>

#### Notebook 02: Cleaning & Merging

In [1]:
import pandas as pd 
import numpy as np
import os

path = os.path.join("..","Data","raw")

customers = pd.read_csv(os.path.join(path,"olist_customers_dataset.csv"))
geolocation = pd.read_csv(os.path.join(path,"olist_geolocation_dataset.csv"))
order_items = pd.read_csv(os.path.join(path,"olist_order_items_dataset.csv"))
payments = pd.read_csv(os.path.join(path,"olist_order_payments_dataset.csv"))
reviews = pd.read_csv(os.path.join(path,"olist_order_reviews_dataset.csv"))
orders = pd.read_csv(os.path.join(path,"olist_orders_dataset.csv"))
products = pd.read_csv(os.path.join(path,"olist_products_dataset.csv"))
sellers = pd.read_csv(os.path.join(path,"olist_sellers_dataset.csv"))
category_name_translation = pd.read_csv(os.path.join(path,"product_category_name_translation.csv"))

## Customers

In [2]:
display(customers.head(3))
print(customers.shape)
print(customers.isnull().sum())

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

(99441, 5)
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [3]:
customers.customer_city = customers.customer_city.str.title() # standardize city names for better analysis

In [4]:
customers.customer_zip_code_prefix = customers.customer_zip_code_prefix.astype("str") # convert zipcode to string for treat it as an identifier
# Zip code must be string to avoid numerical operations

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

## geolocation

In [6]:
display(geolocation.head(3))
print(f"duplicate rows: {geolocation.duplicated().sum()}")
print(geolocation.isnull().sum())
print(geolocation.info())

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

duplicate rows: 261831
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

In [7]:
geolocation.geolocation_city = geolocation.geolocation_city.str.title() # standardize geolocation city
geolocation.geolocation_zip_code_prefix = geolocation.geolocation_zip_code_prefix.astype("str")
geolocation.drop_duplicates(inplace = True) # drops duplicates

In [8]:
print(f"duplicated rows: {geolocation.duplicated().sum()}")

duplicated rows: 0

## order_items

In [9]:
display(order_items.head(3))
print(order_items.info())
print(order_items.isnull().sum())

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [10]:
order_items.shipping_limit_date = pd.to_datetime(order_items.shipping_limit_date) # convert datatype object to datetime

In [11]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

## payments

In [21]:
display(payments.head(3))
print(payments.isnull().sum())
print(f"Duplicated rows: {payments.duplicated().sum()}")
print(payments.info())

,order_id,payment_order,payment_type,payment_installments,payment_amount
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

order_id                0
payment_order           0
payment_type            0
payment_installments    0
payment_amount          0
dtype: int64
Duplicated rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_order         103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_amount        103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

In [13]:
payments.payment_type.unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [14]:
payments.payment_type = payments.payment_type.replace("not_defined","unknown") # replacin not defined with unknown

In [15]:
payments.payment_type.unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'unknown'],
      dtype=object)

In [16]:
payments.rename(columns = {"payment_value":"payment_amount","payment_sequential":"payment_order"}, inplace = True) # renaming column name for redability

In [17]:
payments.head()

,order_id,payment_order,payment_type,payment_installments,payment_amount
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

## reviews

In [22]:
display(reviews.head(3))
print(reviews.isnull().sum())
print(f"Duplicated rows: {reviews.duplicated().sum()}")
print(reviews.info())

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Duplicated rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None